steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/api'
      - '-f'
      - 'api/Dockerfile'
      - '.'

images:
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/api'

substitutions:
  _REGION: asia-northeast3
  _REPO: book-crawler
